### ISSUE TITLE
String comparison without terminating bytes

### ISSUE THREAD

**Issue by bkmgit** [mlichvar/ntp5-exp#1]
Am trying to write a C client. When comparing the draft id at https://github.com/mlichvar/ntp5-exp/blob/main/ntpnode.py#L195 the expected behavior is not clear to me.  Should the length of the string that is compared be the string itself or expanded by 0 to the nearest multiple of 8 octets? The current draft indicates that string terminating characters should not be included so getting the length of the string requires extra operations.

**Comment by bkmgit** [comment]
The last [commit](https://github.com/mlichvar/ntp5-exp/commit/d644436eb8fff6a1215b5b6432f90bf6c4fa6889) modified https://github.com/mlichvar/ntp5-exp/blob/main/ntpnode.py#L77 so perhaps the issue hss been resolved, though maybe helpful to indicate in the draft how these string fields should be compared.

**Comment by mlichvar** [comment]
The length of the string is given by the length of the extension field in which it is contained. It doesn't have to be divisible by 8 or 4.

I opened https://github.com/ietf-wg-ntp/draft-ietf-ntp-ntpv5/pull/13 to make it more clear.
